/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivatePoolTasksGet200ResponseInnerSpentInner {
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "amount")]
    pub amount: String,
}

impl PrivatePoolTasksGet200ResponseInnerSpentInner {
    pub fn new(currency: String, amount: String) -> PrivatePoolTasksGet200ResponseInnerSpentInner {
        PrivatePoolTasksGet200ResponseInnerSpentInner {
            currency,
            amount,
        }
    }
}

