/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivatePoolJoinPost200Response {
    #[serde(rename = "success")]
    pub success: bool,
    #[serde(rename = "task_id")]
    pub task_id: String,
}

impl PrivatePoolJoinPost200Response {
    pub fn new(success: bool, task_id: String) -> PrivatePoolJoinPost200Response {
        PrivatePoolJoinPost200Response {
            success,
            task_id,
        }
    }
}

