/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateWithdrawalsPreparePostRequest {
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "address")]
    pub address: String,
    #[serde(rename = "network")]
    pub network: String,
    #[serde(rename = "memo", skip_serializing_if = "Option::is_none")]
    pub memo: Option<String>,
}

impl PrivateWithdrawalsPreparePostRequest {
    pub fn new(currency: String, amount: String, address: String, network: String) -> PrivateWithdrawalsPreparePostRequest {
        PrivateWithdrawalsPreparePostRequest {
            currency,
            amount,
            address,
            network,
            memo: None,
        }
    }
}

