/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PrivateOrdersCancelPostRequest {
    #[serde(rename = "order_id")]
    pub order_id: String,
    #[serde(rename = "symbol")]
    pub symbol: String,
}

impl PrivateOrdersCancelPostRequest {
    pub fn new(order_id: String, symbol: String) -> PrivateOrdersCancelPostRequest {
        PrivateOrdersCancelPostRequest {
            order_id,
            symbol,
        }
    }
}

