/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicTradesGet200ResponseInner {
    #[serde(rename = "side")]
    pub side: String,
    #[serde(rename = "price")]
    pub price: String,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "cost")]
    pub cost: String,
    #[serde(rename = "created_at")]
    pub created_at: f64,
}

impl PublicTradesGet200ResponseInner {
    pub fn new(side: String, price: String, amount: String, cost: String, created_at: f64) -> PublicTradesGet200ResponseInner {
        PublicTradesGet200ResponseInner {
            side,
            price,
            amount,
            cost,
            created_at,
        }
    }
}

