/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicMarketsGet200ResponseInnerPrecision {
    #[serde(rename = "amount")]
    pub amount: f64,
    #[serde(rename = "cost")]
    pub cost: f64,
    #[serde(rename = "price")]
    pub price: f64,
}

impl PublicMarketsGet200ResponseInnerPrecision {
    pub fn new(amount: f64, cost: f64, price: f64) -> PublicMarketsGet200ResponseInnerPrecision {
        PublicMarketsGet200ResponseInnerPrecision {
            amount,
            cost,
            price,
        }
    }
}

