/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicMarketsTickersListGet200ResponseInner {
    #[serde(rename = "symbol")]
    pub symbol: String,
    #[serde(rename = "last_price")]
    pub last_price: String,
    #[serde(rename = "price_change_percent")]
    pub price_change_percent: String,
    #[serde(rename = "base_volume")]
    pub base_volume: String,
}

impl PublicMarketsTickersListGet200ResponseInner {
    pub fn new(symbol: String, last_price: String, price_change_percent: String, base_volume: String) -> PublicMarketsTickersListGet200ResponseInner {
        PublicMarketsTickersListGet200ResponseInner {
            symbol,
            last_price,
            price_change_percent,
            base_volume,
        }
    }
}

