/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicPoolsFeesHistoryGet200ResponseInner {
    #[serde(rename = "timestamp")]
    pub timestamp: f64,
    #[serde(rename = "fees")]
    pub fees: Box<models::PublicPoolsGet200ResponseInnerEarned24h>,
}

impl PublicPoolsFeesHistoryGet200ResponseInner {
    pub fn new(timestamp: f64, fees: models::PublicPoolsGet200ResponseInnerEarned24h) -> PublicPoolsFeesHistoryGet200ResponseInner {
        PublicPoolsFeesHistoryGet200ResponseInner {
            timestamp,
            fees: Box::new(fees),
        }
    }
}

