/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicOrderbookGet200Response {
    #[serde(rename = "bids")]
    pub bids: Vec<Vec<String>>,
    #[serde(rename = "asks")]
    pub asks: Vec<Vec<String>>,
    #[serde(rename = "timestamp")]
    pub timestamp: f64,
}

impl PublicOrderbookGet200Response {
    pub fn new(bids: Vec<Vec<String>>, asks: Vec<Vec<String>>, timestamp: f64) -> PublicOrderbookGet200Response {
        PublicOrderbookGet200Response {
            bids,
            asks,
            timestamp,
        }
    }
}

