/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicOhlcvGet200ResponseInner {
    #[serde(rename = "time")]
    pub time: f64,
    #[serde(rename = "open")]
    pub open: String,
    #[serde(rename = "high")]
    pub high: String,
    #[serde(rename = "low")]
    pub low: String,
    #[serde(rename = "close")]
    pub close: String,
    #[serde(rename = "volume")]
    pub volume: String,
}

impl PublicOhlcvGet200ResponseInner {
    pub fn new(time: f64, open: String, high: String, low: String, close: String, volume: String) -> PublicOhlcvGet200ResponseInner {
        PublicOhlcvGet200ResponseInner {
            time,
            open,
            high,
            low,
            close,
            volume,
        }
    }
}

