/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicNetworksGet200ResponseInner {
    #[serde(rename = "id")]
    pub id: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "active", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub active: Option<Option<serde_json::Value>>,
    #[serde(rename = "chain_like")]
    pub chain_like: String,
    #[serde(rename = "address_regex", skip_serializing_if = "Option::is_none")]
    pub address_regex: Option<String>,
    #[serde(rename = "withdrawal_fee_usd")]
    pub withdrawal_fee_usd: f64,
    #[serde(rename = "min_deposit_usd")]
    pub min_deposit_usd: f64,
    #[serde(rename = "logo_url")]
    pub logo_url: String,
    #[serde(rename = "min_confirmations")]
    pub min_confirmations: f64,
    #[serde(rename = "memo_support", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub memo_support: Option<Option<serde_json::Value>>,
    #[serde(rename = "explorer_txid")]
    pub explorer_txid: String,
    #[serde(rename = "explorer_address")]
    pub explorer_address: String,
    #[serde(rename = "native_currency")]
    pub native_currency: String,
}

impl PublicNetworksGet200ResponseInner {
    pub fn new(id: String, name: String, chain_like: String, withdrawal_fee_usd: f64, min_deposit_usd: f64, logo_url: String, min_confirmations: f64, explorer_txid: String, explorer_address: String, native_currency: String) -> PublicNetworksGet200ResponseInner {
        PublicNetworksGet200ResponseInner {
            id,
            name,
            active: None,
            chain_like,
            address_regex: None,
            withdrawal_fee_usd,
            min_deposit_usd,
            logo_url,
            min_confirmations,
            memo_support: None,
            explorer_txid,
            explorer_address,
            native_currency,
        }
    }
}

