/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicExkConfigGet200ResponseWeeklyDist {
    #[serde(rename = "cycle_id")]
    pub cycle_id: f64,
    #[serde(rename = "timestamp_to_next_dist")]
    pub timestamp_to_next_dist: f64,
    #[serde(rename = "total_points")]
    pub total_points: f64,
    #[serde(rename = "points_for")]
    pub points_for: std::collections::HashMap<String, f64>,
}

impl PublicExkConfigGet200ResponseWeeklyDist {
    pub fn new(cycle_id: f64, timestamp_to_next_dist: f64, total_points: f64, points_for: std::collections::HashMap<String, f64>) -> PublicExkConfigGet200ResponseWeeklyDist {
        PublicExkConfigGet200ResponseWeeklyDist {
            cycle_id,
            timestamp_to_next_dist,
            total_points,
            points_for,
        }
    }
}

