/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicGainsLossesTransparencyGet200ResponseLast20Inner {
    #[serde(rename = "currency")]
    pub currency: String,
    #[serde(rename = "network", deserialize_with = "Option::deserialize")]
    pub network: Option<String>,
    #[serde(rename = "amount")]
    pub amount: String,
    #[serde(rename = "reason")]
    pub reason: String,
    #[serde(rename = "timestamp")]
    pub timestamp: f64,
}

impl PublicGainsLossesTransparencyGet200ResponseLast20Inner {
    pub fn new(currency: String, network: Option<String>, amount: String, reason: String, timestamp: f64) -> PublicGainsLossesTransparencyGet200ResponseLast20Inner {
        PublicGainsLossesTransparencyGet200ResponseLast20Inner {
            currency,
            network,
            amount,
            reason,
            timestamp,
        }
    }
}

