/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicGainsLossesTransparencyGet200ResponseCurrenciesValue {
    #[serde(rename = "total")]
    pub total: String,
    #[serde(rename = "trades")]
    pub trades: String,
    #[serde(rename = "exk_program")]
    pub exk_program: String,
    #[serde(rename = "withdrawals")]
    pub withdrawals: String,
    #[serde(rename = "transfers")]
    pub transfers: String,
    #[serde(rename = "admin_withdrawals")]
    pub admin_withdrawals: String,
    #[serde(rename = "admin_deposits")]
    pub admin_deposits: String,
}

impl PublicGainsLossesTransparencyGet200ResponseCurrenciesValue {
    pub fn new(total: String, trades: String, exk_program: String, withdrawals: String, transfers: String, admin_withdrawals: String, admin_deposits: String) -> PublicGainsLossesTransparencyGet200ResponseCurrenciesValue {
        PublicGainsLossesTransparencyGet200ResponseCurrenciesValue {
            total,
            trades,
            exk_program,
            withdrawals,
            transfers,
            admin_withdrawals,
            admin_deposits,
        }
    }
}

