/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicMarketsGet200ResponseInnerLimitsPrice {
    #[serde(rename = "min", skip_serializing_if = "Option::is_none")]
    pub min: Option<String>,
    #[serde(rename = "max", skip_serializing_if = "Option::is_none")]
    pub max: Option<String>,
}

impl PublicMarketsGet200ResponseInnerLimitsPrice {
    pub fn new() -> PublicMarketsGet200ResponseInnerLimitsPrice {
        PublicMarketsGet200ResponseInnerLimitsPrice {
            min: None,
            max: None,
        }
    }
}

