/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicFundsTransparencyGet200ResponseStatsValue {
    #[serde(rename = "total")]
    pub total: f64,
    #[serde(rename = "in_cold")]
    pub in_cold: f64,
    #[serde(rename = "total_user_owned")]
    pub total_user_owned: f64,
    #[serde(rename = "reserve")]
    pub reserve: String,
}

impl PublicFundsTransparencyGet200ResponseStatsValue {
    pub fn new(total: f64, in_cold: f64, total_user_owned: f64, reserve: String) -> PublicFundsTransparencyGet200ResponseStatsValue {
        PublicFundsTransparencyGet200ResponseStatsValue {
            total,
            in_cold,
            total_user_owned,
            reserve,
        }
    }
}

