/*
 * ExKoin API Documentation
 *
 * API documentation for ExKoin Crypto exchange
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PublicForexPricesGet200Response {
    #[serde(rename = "prices_usd")]
    pub prices_usd: std::collections::HashMap<String, f64>,
    #[serde(rename = "symb_to_name")]
    pub symb_to_name: std::collections::HashMap<String, String>,
}

impl PublicForexPricesGet200Response {
    pub fn new(prices_usd: std::collections::HashMap<String, f64>, symb_to_name: std::collections::HashMap<String, String>) -> PublicForexPricesGet200Response {
        PublicForexPricesGet200Response {
            prices_usd,
            symb_to_name,
        }
    }
}

